<div>
    <?php if (isset($message)) {

        echo $message;
    }
    ?>
    <form method="post" action="" class="form w-50 m-auto">
        <!-- <input type="text" name="pname" placeholder="productname"> -->

        <p> <input type="text" name="username" placeholder="name" class="form-control"></p>

        <p> <input type="text" name="url" placeholder="url" class="form-control"></p>
        <!-- <p> <input type="text" name="key" placeholder="key" class="form-control"></p> -->
        <p> <input type="text" name="token" placeholder="token" class="form-control"></p>
        <!-- <p> <input type="number" name="quantity" class="form-control" placeholder="quantity"></p> -->

        <p> <input type="submit" name="submit" value="addproduct Hook" class="form-control btn btn-primary"></p>
    </form>
    <form method="post" action="" class="form w-50 m-auto">
        <!-- <input type="text" name="pname" placeholder="productname"> -->

        <p> <input type="text" name="username" placeholder="name" class="form-control"></p>

        <p> <input type="text" name="url" placeholder="url" class="form-control"></p>
        <!-- <p> <input type="text" name="key" placeholder="key" class="form-control"></p> -->
        <p> <input type="text" name="token" placeholder="token" class="form-control"></p>
        <!-- <p> <input type="number" name="quantity" class="form-control" placeholder="quantity"></p> -->

        <p> <input type="submit" name="edit" value="update product Hook" class="form-control btn btn-primary"></p>
    </form>
</div>