<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <!-- <h2>rererererererererererere</h2> -->

    <form method="post" action="updateproduct" class="form w-50 m-auto">


        <p><input type="text" name="skuid" placeholder="sktuid" class="form-control" disabled  value=<?php echo  $message['skuid'] ?>></p>
        <p><input type="text" name="productname" placeholder="sktuid" class="form-control" disabled  value=<?php echo  $message['productname'] ?>></p>
        <p><input type="text" name="price" placeholder="sktuid" class="form-control" value=<?php echo  $message['price'] ?>></p>
        <p><input type="hidden" name="skuid" placeholder="sktuid" class="form-control"  value=<?php echo  $message['skuid'] ?>></p>
        <p><input type="text" name="quantity" placeholder="sktuid" class="form-control" value=<? echo $message['quantity'] ?>></p>
        <p><input type="submit" name="update" value="update" class="btn btn-primary"></p>
    </form>
</body>

</html>