<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="m-5">


    <form action="" method="post" class="form w-50 m-auto ">
      
        <input type="text" name="email" class="form-control m-4" placeholder= <?php echo $this->locale->_("email") ?>>
        <input type="text" name="password" class="form-control m-4"  placeholder=<?php echo $this->locale->_("password") ?>>
        <input type="submit" name="submit"  class="form-control btn btn-primary m-4" value=<?php echo $this->locale->_("login") ?>>

    </form>
    <a href="register"   class="form-control btn btn-primary m-4 w-50 m-auto " >Register User</a>
  
    </div>
  

</body>

</html>